exclude: '^(libffi.*|portaudio)/'
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.0'
    hooks:
    -   id: clang-format
        files: '.*\.(h|cpp|t|mm|c)$'
        exclude: '^(libffi.*|portaudio|Packages|Resources|Drivers)/'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-yaml
