// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLAppUI_h
#define TFLAppUI_h
#include <FL/Fl.H>
#include "TFLAppWindow.h"
void draw_ramp(int x, int y, int w, int h, Fl_Color c);
extern TFLAppWindow *wAppWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wPowerTool;
extern Fl_Button *wPowerOnTool;
extern Fl_Button *wBacklightTool;
extern Fl_Button *wBacklightOnTool;
extern Fl_Button *wNetworkTool;
extern Fl_Button *wNetworkOnTool;
#include <FL/Fl_Box.H>
extern Fl_Box *wSpacer;
TFLAppWindow* CreateApplicationWindow(int x, int y);
extern Fl_Menu_Item menu_wMenubar[];
#define wMenuItemFullscreen (menu_wMenubar+29)
#define wMenuItemMonitor (menu_wMenubar+30)
#define wMenuItemToolkit (menu_wMenubar+31)
#endif
