// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLAppUI_h
#define TFLAppUI_h
#include <FL/Fl.H>
#include "TFLAppWindow.h"
#include "TFLTabs.h"
extern unsigned char imgPCCardTopIn[3083];
extern unsigned char imgPCCardTopOut[3176];
extern unsigned char imgPCCardTopHilite[3280];
extern unsigned char imgPCCardBotIn[3102];
extern unsigned char imgPCCardBotOut[3176];
extern unsigned char imgPCCardBotHilite[3294];
extern TFLAppWindow *wAppWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wPowerTool;
extern Fl_Button *wPowerOnTool;
extern Fl_Button *wBacklightTool;
extern Fl_Button *wBacklightOnTool;
extern TFLPCMCIAButton *wNetworkTool;
extern Fl_Button *wNetworkOnTool;
#include <FL/Fl_Box.H>
extern Fl_Box *wSpacer;
TFLAppWindow* CreateApplicationWindow(int x, int y);
extern Fl_Menu_Item menu_wMenubar[];
#define wPCCardSlot0 (menu_wMenubar+24)
#define wPCCardSlot1 (menu_wMenubar+25)
#define wMenuItemFullscreen (menu_wMenubar+30)
#define wMenuItemMonitor (menu_wMenubar+31)
#define wMenuItemToolkit (menu_wMenubar+32)
#endif
