// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLAppUI_h
#define TFLAppUI_h
#include <FL/Fl.H>
#include "TFLAppWindow.h"
extern TFLAppWindow *wAppWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wToolbox;
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
extern Fl_Box *wSpacer;
TFLAppWindow* CreateApplicationWindow();
extern Fl_Menu_Item menu_wMenubar[];
#endif
