// generated by Fast Light User Interface Designer (fluid) version 1.0400

#include "TFLInspectorUI.h"
#include "TFLApp.h"
#include <FL/fl_draw.H>

Fl_Double_Window *wInspectorWindow=(Fl_Double_Window *)0;

Fl_Menu_Bar *wInspectorMenubar=(Fl_Menu_Bar *)0;

static void cb_Quit(Fl_Menu_*, void*) {
  gApp->UserActionQuit();
}

static void cb_Run(Fl_Menu_*, void*) {
  gApp->UserActionInspectorRun();
}

Fl_Menu_Item menu_wInspectorMenubar[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"New...", FL_COMMAND|0x1006e,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open...", FL_COMMAND|0x1006f,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Save", FL_COMMAND|0x10073,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Save As...", 0,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Close", FL_COMMAND|0x10077,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 17, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 17, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 17, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 17, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 145, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Page Setup...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Print...", FL_COMMAND|0x10070,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", FL_COMMAND|0x71,  (Fl_Callback*)cb_Quit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Edit", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Cut", FL_COMMAND|0x10078,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Copy", FL_COMMAND|0x10063,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Paste", FL_COMMAND|0x10076,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Application", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Build", FL_COMMAND|0x62,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Install", FL_COMMAND|0x32,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Run", FL_COMMAND|0x72,  (Fl_Callback*)cb_Run, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Inspector Manual...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"About Inspector...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Group *wInspectorToolbar=(Fl_Group *)0;

Fl_Button *wInspectorRun=(Fl_Button *)0;

static void cb_wInspectorRun(Fl_Button*, void*) {
  gApp->UserActionInspectorRun();
}

Fl_Text_Editor *wInspectorEditor=(Fl_Text_Editor *)0;

Fl_Text_Display *wInspectorTerminal=(Fl_Text_Display *)0;

Fl_Double_Window* CreateInspectorWindow(int x, int y) {
  { wInspectorWindow = new Fl_Double_Window(720, 600);
    { Fl_Menu_Bar* o = wInspectorMenubar = new Fl_Menu_Bar(0, 0, 720, 24);
      wInspectorMenubar->color(FL_LIGHT2);
      wInspectorMenubar->menu(menu_wInspectorMenubar);
      o->box(FL_FREE_BOXTYPE);
    } // Fl_Menu_Bar* wInspectorMenubar
    { Fl_Group* o = wInspectorToolbar = new Fl_Group(0, 24, 720, 54);
      wInspectorToolbar->box(FL_THIN_UP_BOX);
      wInspectorToolbar->color(FL_LIGHT2);
      { Fl_Button* o = wInspectorRun = new Fl_Button(10, 25, 36, 36, "@>");
        wInspectorRun->color(FL_LIGHT2);
        wInspectorRun->labelsize(24);
        wInspectorRun->labelcolor((Fl_Color)48);
        wInspectorRun->callback((Fl_Callback*)cb_wInspectorRun);
        wInspectorRun->align(Fl_Align(512|FL_ALIGN_INSIDE));
        o->box(FL_FREE_BOXTYPE);
        o->down_box(FL_FREE_BOXTYPE);
        o->clear_visible_focus();
      } // Fl_Button* wInspectorRun
      o->box(FL_FREE_BOXTYPE);
      wInspectorToolbar->end();
    } // Fl_Group* wInspectorToolbar
    { Fl_Box* o = new Fl_Box(0, 78, 320, 480);
      o->hide();
    } // Fl_Box* o
    { wInspectorEditor = new Fl_Text_Editor(0, 78, 720, 422);
      wInspectorEditor->box(FL_THIN_DOWN_FRAME);
      wInspectorEditor->selection_color((Fl_Color)246);
      wInspectorEditor->textfont(4);
      Fl_Group::current()->resizable(wInspectorEditor);
    } // Fl_Text_Editor* wInspectorEditor
    { wInspectorTerminal = new Fl_Text_Display(0, 500, 720, 100);
      wInspectorTerminal->box(FL_THIN_DOWN_FRAME);
      wInspectorTerminal->selection_color((Fl_Color)246);
      wInspectorTerminal->textfont(4);
    } // Fl_Text_Display* wInspectorTerminal
    wInspectorWindow->position(x, y);
    wInspectorWindow->end();
  } // Fl_Double_Window* wInspectorWindow
  return wInspectorWindow;
}
