// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLInspectorUI_h
#define TFLInspectorUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *wInspectorWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wInspectorMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wInspectorToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wInspectorRun;
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *wInspectorEditor;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *wInspectorTerminal;
Fl_Double_Window* CreateInspectorWindow(int x, int y);
extern Fl_Menu_Item menu_wInspectorMenubar[];
#endif
