// ==============================
// File:			TFLSettings
// Project:			Einstein
//
// Copyright 2003-2007 by Paul Guyot (pguyot@kallisys.net).
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
// ==============================
// $Id$
// ==============================

// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef TFLSettings_h
#define TFLSettings_h
#include <FL/Fl.H>
class TFLApp;
#include <FL/Fl_Window.H>
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Check_Button.H>

class TFLSettings : public Fl_Window {
  void _TFLSettings();
public:
  TFLSettings(int X, int Y, int W, int H, const char *L = 0);
  TFLSettings(int W, int H, const char *L = 0);
  Fl_Menu_Button *RMB;
  static Fl_Menu_Item menu_RMB[];
private:
  void cb_Power_i(Fl_Menu_*, void*);
  static void cb_Power(Fl_Menu_*, void*);
  void cb_Backlight_i(Fl_Menu_*, void*);
  static void cb_Backlight(Fl_Menu_*, void*);
  void cb_Install_i(Fl_Menu_*, void*);
  static void cb_Install(Fl_Menu_*, void*);
  void cb_Settings_i(Fl_Menu_*, void*);
  static void cb_Settings(Fl_Menu_*, void*);
  void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  static Fl_Menu_Item menu_Machine[];
  static Fl_Menu_Item menu_Flash[];
  static Fl_Menu_Item menu_RAM[];
  TFLApp *app; 
public:
  void setApp(TFLApp *App);
};
#include <FL/Fl_Double_Window.H>
extern void close_window_cb(Fl_Double_Window*, void*);
extern Fl_Double_Window *wAbout;
extern void close_window_cb(Fl_Button*, void*);
Fl_Double_Window* createAboutDialog();
#endif

// ======================================================== //
// Of course the code works. It just compiled, didn't it?   //
// --helixcode123, 11/8/2001 on slashdot.                   //
// ======================================================== //


