// generated by Fast Light User Interface Designer (fluid) version 1.0405

#include "TFLSampleScripts.h"

const char *kToolkitSampleScriptHelloWorld = /* text inlined from SampleScripts/HelloWorld.ns */
"//\n// NewtonScript example: Hello, World!\n//\n\nkAppName := \"Hello:WONKO\""
";\nkAppSymbol := \'|Hello:WONKO|;\nkAppLabel := \"Hello\";\n\nnewt.theForm := "
"{\n\tviewBounds: {\n\t\tleft: 0, top: 50, right: 200, bottom: 120\n\t},\n\t_pr"
"oto: protoFloatNGo\n};\n\nhelloButton := {\n\ttext: \"Say Hello\",\n\tviewBoun"
"ds: {\n\t\tleft: 50, top: 25, right: 150, bottom: 50\n\t},\n\tbuttonClickScrip"
"t: func()\n\tbegin\n\t\tModalConfirm(\n\t\t\t\"Hello World of NewtonScript.\\r"
"\\rHow exciting to see you!\",\n\t\t\t[ \"OK\" ]\n\t\t);\n\tend,\n\t_proto: pr"
"otoTextButton\n};\nAddStepForm( newt.theForm, helloButton);\nStepDeclare( newt"
".theForm, helloButton, \'helloButton);\n";

const char *kToolkitSampleScriptMPG = /* text inlined from SampleScripts/mpg.ns */
"//\n// This little app calculates the range of a car in mpg,\n// \"miles per "
"gallon\", based on the distance driven and \n// the number of gallons of gasol"
"ine used.\n//\n\nkAppName := \"MPG:WONKO\";\nkAppSymbol := \'|MPG:WONKO|;\nkAp"
"pLabel := \"MPG\";\n\n// The main form can be moved around the screen\nnewt.th"
"eForm := {\n\tviewBounds: {\n\t\tleft: 0, top: 30, right: 180, bottom: 220\n\t"
"},\n\t_proto: protoFloatNGo,\n\trecalculateMileage: func() \n\tbegin\n\t\tloca"
"l trip := wTrip.value;\n\t\tlocal gas := wGas.value;\n\t\tlocal mileage := 999"
";\n\t\tif gas > 0 then\n\t\t\tmileage := trip / gas;\n\t\tSetValue( wMileage, "
"\'value, floor( mileage) );\n\tend\n};\n\n// Give the app a little title bar\n"
"wTitle := {\n\t_proto: protoStaticText, \n\ttext: \"MPG\", \n\tviewBounds: {\n"
"\t\tleft: 61, top: 3, bottom: 22, right: 112\n\t}, \n\tviewFont: ROM_fontSyste"
"m12Bold\n};\nAddStepForm( newt.theForm, wTitle);\nStepDeclare( newt.theForm, w"
"Title, \'wTitle);\n\n// I want a headline, too\nwHeadline := {\n\t_proto: prot"
"oStaticText,\n\ttext: \"calculate your gas milage\",\n\tviewBounds: {\n\t\tlef"
"t: 11, top: 22, bottom: 41, right: 163\n\t},\n\tviewFont: ROM_fontSystem10Bold"
"\n};\nAddStepForm( newt.theForm, wHeadline);\nStepDeclare( newt.theForm, wHead"
"line, \'wHeadline);\n\n// Just because we can, here is a badly drawn icon\nwIc"
"on := {\n\tviewClass: clPictureView,\n\tviewFlags: vVisible,\n\tviewFormat: vf"
"FillWhite,\n\tviewJustify: vjCenterV + vjCenterH,\n\ticon: MakeIconFromFile(\""
"embedded:/mpg.png\"),\n\tviewBounds: {\n\t\tleft: 30, top: 88, bottom: 121, ri"
"ght: 64\n\t}\n};\nAddStepForm( newt.theForm, wIcon);\nStepDeclare( newt.theFor"
"m, wIcon, \'wIcon);\n\n// Trip distance in miles since last fill up\nwTrip := "
"{\n\t_proto: protoNumberPicker, \n\tpreallocatedContext: \'wTrip,\n\tvalue: 0,"
" \n\tmaxValue: 9999, \n\tminValue: 0, \n\tviewBounds: {\n\t\tleft: 51, top: 50"
", bottom: 81, right: 140\n\t}, \n\tClickDone: func()\n\tbegin\n\t\t:recalculat"
"eMileage();\n\tend\n};\nAddStepForm( newt.theForm, wTrip);\nStepDeclare( newt."
"theForm, wTrip, \'wTrip);\n\n// Amount of gasoline needed after trip for a com"
"plete refill\nwGas := {\n\t_proto: protoNumberPicker, \n\tvalue: 0, \n\tmaxVal"
"ue: 999, \n\tminValue: 0, \n\tviewBounds: {\n\t\tleft: 73, top: 90, bottom: 12"
"1, right: 140\n\t}, \n\tClickDone: func()\n\tbegin\n\t\t:recalculateMileage();"
"\n\tend\n};\nAddStepForm( newt.theForm, wGas);\nStepDeclare( newt.theForm, wGa"
"s, \'wGas);\n\n// Show the miles of range per gallon of gasoline used\nwMileag"
"e := {\n\t_proto: protoNumberPicker, \n\tvalue: 999, \n\tmaxValue: 999, \n\tmi"
"nValue: 0, \n\tviewBounds: {\n\t\tleft: 73, top: 130, bottom: 161, right: 140"
"\n\t}\n};\nAddStepForm( newt.theForm, wMileage);\nStepDeclare( newt.theForm, w"
"Mileage, \'wMileage);\n\nwTripLabel := {\n\t_proto: protoStaticText, \n\ttext:"
" \"mi\", \n\tviewBounds: {\n\t\tleft: 142, top: 62, bottom: 80, right: 166\n\t"
"}\n};\nAddStepForm( newt.theForm, wTripLabel);\nStepDeclare( newt.theForm, wTr"
"ipLabel, \'wTripLabel);\n\nwGasLabel := {\n\t_proto: protoStaticText, \n\ttext"
": \"gal\", \n\tviewBounds: {\n\t\tleft: 142, top: 101, bottom: 120, right: 166"
"\n\t}\n};\nAddStepForm( newt.theForm, wGasLabel);\nStepDeclare( newt.theForm, "
"wGasLabel, \'wGasLabel);\n\nwMileageLabel := {\n\t_proto: protoStaticText, \n"
"\ttext: \"mpg\", \n\tviewBounds: {\n\t\tleft: 142, top: 141, bottom: 161, righ"
"t: 168\n\t}\n};\nAddStepForm( newt.theForm, wMileageLabel);\nStepDeclare( newt"
".theForm, wMileageLabel, \'wMileageLabel);\n\n";

unsigned char kToolkitSampleImageMPG[1246] = /* data inlined from SampleScripts/mpg.png */
{137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,6,0,0,0,
115,122,122,244,0,0,0,9,112,72,89,115,0,0,5,19,0,0,5,19,1,90,59,202,79,0,0,4,
144,73,68,65,84,88,71,173,151,93,72,101,85,20,199,247,241,154,230,71,140,69,49,
48,32,248,48,96,12,210,8,97,137,16,222,162,124,244,205,200,151,129,32,18,177,
39,75,198,151,222,122,9,31,44,98,24,2,123,182,55,17,95,66,148,33,36,193,145,
153,210,241,201,1,63,34,210,102,30,198,145,201,143,171,247,158,214,111,123,214,
101,117,58,231,232,29,218,240,103,127,156,189,214,250,239,181,215,94,123,31,231,
156,123,77,112,79,112,42,40,69,117,65,234,19,1,53,227,199,177,113,253,150,84,63,
147,185,179,130,235,130,11,149,15,35,229,161,212,255,23,32,125,251,34,214,171,
101,210,43,130,128,201,245,245,245,46,159,207,187,230,230,102,136,4,82,194,82,
169,20,228,114,57,95,155,190,147,126,121,78,161,80,8,214,215,215,195,165,165,
165,224,228,4,167,184,156,160,237,34,4,152,243,41,30,168,173,173,13,103,102,102,
194,227,227,99,140,149,78,79,79,75,162,172,92,23,139,69,250,82,249,218,143,235,
28,250,219,219,219,133,254,254,126,182,80,189,200,86,188,119,30,9,60,0,219,98,
119,119,119,174,167,167,199,137,34,55,53,53,197,106,93,93,93,157,59,60,60,116,
97,136,78,239,161,64,251,124,199,99,7,7,7,174,163,163,3,207,85,247,245,245,185,
201,201,73,181,217,32,141,111,5,29,130,163,44,34,3,242,241,100,96,96,32,148,213,
137,173,231,46,165,217,217,89,235,1,88,19,11,159,103,25,175,146,143,32,100,69,
226,249,243,60,150,245,61,168,170,66,213,191,10,222,189,41,184,150,38,136,68,81,
16,168,155,43,101,48,62,62,238,118,118,118,16,35,118,146,196,57,230,223,8,106,
147,62,66,0,150,126,147,241,2,101,108,108,204,173,174,174,250,246,200,200,72,97,
113,113,209,107,30,29,29,117,211,211,211,196,72,89,23,49,211,216,216,24,137,159,
201,39,148,188,140,221,72,35,128,114,239,62,245,130,196,130,91,88,88,112,187,
187,187,174,169,169,137,100,228,53,111,110,110,122,29,173,173,173,174,183,183,
215,109,109,109,121,162,4,43,139,136,121,17,57,45,47,72,227,107,193,27,113,18,
156,2,95,112,159,122,128,122,104,104,200,143,183,183,183,55,116,117,117,5,43,43,
43,254,68,96,152,239,144,216,219,219,115,157,157,157,174,186,218,171,129,228,
217,113,57,171,255,16,180,8,52,48,94,150,246,247,2,142,230,161,37,50,40,157,194,
224,224,96,40,9,37,245,8,144,31,64,86,153,155,155,211,83,64,125,71,240,48,34,
163,185,129,227,152,183,198,97,199,81,169,58,58,58,114,9,81,92,158,91,83,83,227,
64,90,193,253,178,117,26,4,212,164,196,79,4,127,27,25,20,124,38,32,238,124,129,
0,254,43,46,47,47,251,164,242,188,133,109,33,118,162,162,43,254,89,250,183,
208,31,141,67,140,45,120,203,18,224,99,110,109,109,205,205,207,207,59,73,175,
101,14,26,84,105,53,19,245,219,254,254,190,147,211,162,178,24,210,189,231,8,18,
15,90,46,73,227,35,237,176,122,192,158,229,134,135,135,221,198,198,134,107,107,
107,243,129,134,242,172,90,9,72,108,120,227,19,19,19,214,3,154,20,72,18,63,10,
190,192,70,68,236,93,169,57,187,220,23,254,50,98,191,42,189,138,109,218,141,167,
96,116,241,38,208,242,182,52,246,141,141,39,210,230,142,240,110,242,169,216,76,
190,72,211,206,79,146,213,197,168,174,95,165,177,109,20,191,36,237,119,148,0,
117,106,10,51,66,184,75,141,217,249,73,178,140,145,130,181,144,148,126,17,232,
182,176,232,46,236,86,178,122,8,168,130,243,60,128,225,171,130,87,13,137,187,70,
30,130,151,5,185,74,182,192,11,68,10,207,243,0,211,120,15,176,74,45,118,1,58,
22,66,128,85,253,231,30,53,130,218,180,70,227,30,72,138,3,116,18,224,220,3,148,
43,198,14,243,201,138,158,128,94,201,9,54,83,135,32,99,179,94,90,12,113,220,62,
136,180,180,24,15,50,244,23,139,87,227,229,212,88,9,139,104,110,60,226,173,138,
122,233,124,37,32,22,154,205,7,100,30,209,215,55,161,79,68,9,198,253,203,215,24,
210,27,207,222,124,220,108,47,102,16,231,255,224,39,1,65,105,61,245,187,18,240,
239,129,20,227,246,122,141,95,183,42,130,241,172,24,226,219,155,49,253,252,232,
144,27,188,7,210,74,124,159,179,230,197,191,65,156,179,159,248,12,147,241,117,1,
127,99,158,185,93,153,42,178,43,103,44,222,79,26,179,39,1,157,188,5,118,141,172,
202,60,150,198,151,2,127,15,224,1,187,207,89,138,45,9,149,73,34,166,139,248,83,
26,28,195,143,5,60,197,184,117,127,19,252,32,184,111,93,214,35,157,167,17,145,
74,47,164,180,249,24,251,206,24,225,33,146,122,210,216,39,88,249,196,32,176,
207,42,53,16,31,203,154,195,131,226,129,224,117,187,202,180,182,70,63,145,204,
31,210,251,2,125,119,105,16,198,207,185,189,63,116,43,152,11,41,128,113,94,65,
246,246,75,229,242,15,250,180,154,148,197,197,251,39,0,0,0,0,73,69,78,68,174,66,
96,130};

const char *kToolkitSampleScriptNativeFunction = /* text inlined from SampleScripts/NativeFunction.ns */
"//\n// NewtonScript example: Native Call\n//\n// How to write ARM machine cod"
"e within NewtonScript.\n//\n\nkAppName := \"Hello:WONKO\";\nkAppSymbol := \'|H"
"ello:WONKO|;\nkAppLabel := \"Hello\";\n\nnewt.theForm := {\n\tviewBounds: {\n"
"\t\tleft: 0, top: 50, right: 200, bottom: 120\n\t},\n_proto: protoFloatNGo\n};"
"\n\nmathFunction := {\n\t_proto: protoStaticText,\n\ttext: \"4+8 =\",\n\tviewB"
"ounds: RelBounds(50, 25, 30, 20)\n};\nAddStepForm(newt.theForm, mathFunction);"
"\nStepDeclare(newt.theForm, mathFunction, \'mathFunction);\n\nmathResult := {"
"\n\t_proto: protoStaticText,\n\tnativeMath: {\n\t\tclass : \'BinCFunction,\n\t"
"\tnumArgs: 2,\n\t\toffset: 0,\n\t\tcode: MakeBinaryFromARM(\"\n\t\t\tldr r1, ["
"r1]\t\t\t@ Unref the first argument\n\t\t\tldr r1, [r1]\t\t\t@ Get the integer"
" object\n\t\t\tmov r1, r1, lsr #2\t\t@ convert it into an integer\n\t\t\tldr r"
"2, [r2]\n\t\t\tldr r2, [r2]\t\t\t@ do the same with the second arg\n\t\t\tmov "
"r2, r2, lsr #2\n\t\t\tadd r0, r1, r2\t\t\t@ add both integers\n\t\t\tmov r0, r"
"0, lsl #2\t\t@ convert the result into an integer object\n\t\t\tmov pc, lr\t\t"
"\t\t@ return to the interpreter\n\t\t\t\")\n\t},\n\tnewtonScriptMath: func(a, "
"b) begin\n\t\treturn a+b;\n\tend,\n\tViewSetupFormScript: func() begin\n\t\tSe"
"tValue(self, \'text, NumberStr( self:nativeMath(4, 8) ) );\n\tend,\n\ttext: \""
"Result\",\n\tviewBounds: RelBounds(80, 25, 80, 20)\n};\nAddStepForm(newt.theFo"
"rm, mathResult);\nStepDeclare(newt.theForm, mathResult, \'mathResult);\n\n";

const char *kToolkitSampleScriptROMPatcher = /* text inlined from SampleScripts/ROMPatcher.ns */
"//\n// Patch a ROM file with a backdoor.\n//\n// This patch for Newton Flash "
"ROM Cards makes it possible\n// for Newton apps to modify the contents of thos"
"e cards.\n//\n\n// TODO: use fltk:message to warn the user\n// TODO: use fltk:"
"choice to let the user aselect a ROM type (eMate, US, D, FR)\n// TODO: let the"
" user choose the ROM file using fltk:filechooser\n\n// Patch the US ROM:\nPatc"
"hFileFromARM(\"\n\t.org 0x003ADD24\n\n\t@\t\n\t@ Patch the SWI12 in the US ROM"
"\n\t@\n\tb testForBackdoor\n\n\t.org 0x007ff000\n\n\t@ Jump Table for various "
"functions in this patch\n\ntestForBackdoor:\n\tb doTestForBackdoor\nsetCoproCo"
"ntrol:\n\tb doSetCoproControl\n\n\t@\t\n\t@ Check if this is a call for openin"
"g the backdoor\n\t@\tparam r0 0x0BADCAFE to activate backdoor\n\t@\tparam r1 s"
"witch to SVC and jump here\n\t@\treturn r0 return to this address to leave SVC"
" mode\n\t@\n\tldr r1, =0x0BADCAFE\t@ this is our secret password\n\tcmp r0, r1"
"\t\t\t@ is that set in r0?\n\tbne 0x003ADD28\t\t@ nope, just continue as if no"
"thing happened\n\tldmia r13!, {r0, r1}@ get r0 and r1 from the stack\n\tmov r0"
", pc\t\t\t@ suggest a return address to the caller\n\tmov pc, r1\t\t\t@ jump t"
"o the address supplied in r1\n\tb 0x003ADD38\t\t@ safely finish the SWI\n\n\t@"
"\n\t@ Set the Control register in the Coprocessor\n\t@\tparam r0 new value for"
" Control register\n\t@\tparam lr return address\n\t@\n\tmcr p15, 0, r0, c1, c1"
", 0\n\tnop\t\t\t\t\t@ flush instruction cache after MMU changes\n\tnop\n\tnop"
"\n\tnop\n\tmov pc, lr\t\t\t@ return \n\t\",\n\t\"fakeROM\"\n);\n";
