// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef TFLSampleScripts_h
#define TFLSampleScripts_h
extern const char *kToolkitSampleScriptHelloWorld;
extern const char *kToolkitSampleScriptMPG;
extern unsigned char kToolkitSampleImageMPG[1246];
extern const char *kToolkitSampleScriptNativeFunction;
extern const char *kToolkitSampleScriptROMPatcher;
#endif
