// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLSampleScripts_h
#define TFLSampleScripts_h
extern const char *kToolkitSampleScriptHelloWorld;
extern const char *kToolkitSampleScriptNativeFunction;
#endif
