// generated by Fast Light User Interface Designer (fluid) version 1.0400

#ifndef TFLToolkitUI_h
#define TFLToolkitUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *wToolkitWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wToolkitMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wToolkitToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wToolkitRun;
extern Fl_Button *wToolkitStop;
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Editor.H>
extern Fl_Text_Editor *wToolkitEditor;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *wToolkitTerminal;
Fl_Double_Window* CreateToolkitWindow(int x, int y);
extern Fl_Menu_Item menu_wToolkitMenubar[];
#endif
