// generated by Fast Light User Interface Designer (fluid) version 1.0405

#include "TFLToolkitUI.h"
#include "Toolkit/TToolkit.h"
#include "app/FLTK/TFLApp.h"
#include <FL/fl_draw.H>
#include <FL/Fl_Help_Dialog.H>
Fl_Menu_Item *wTKOpenRecentMenu[8];
static Fl_Help_Dialog *tkHelpDialog = nullptr;

static const char *tkHelpText = /* text inlined from TTkHelpText.html */
"<html>\n<body>\n\n<h1>NewtonScript Extensions</h1>\n\n<h2>Globals</h2>\n\n<b>"
"MakeBinaryFromString(str, sym)</b>: Generate a binary object with the given\ns"
"ymbol from an Unicode text. The input format is UTF-8. The format of the binar"
"y\nobject is UTF-8 for newt/64, but it is converted to UTF-16 when written int"
"o\na 32 bit package or streaming package, and the symbol is <tt>\'string</tt>."
"\n\n<p>\n<b>PatchFileFromARM(ARM_Instructions, filename)</b>: This global func"
"tion\nis a little helper for a very specific job. The first argument is a stri"
"ng\nwith ARM assembler instructions, usually starting with <tt>org address</tt"
"> to\ndefine the position in the binary. The second argument is the the file p"
"ath and\nname of an ARM binary, usually the NewtonOS ROM file. Calling\n<tt>Pa"
"tchFileFromARM</tt> will assemble and link the ARM code into ARM commends\nand"
" then overwrite the code in the ROM file with the new ARM code at the\ngiven a"
"ddresses.\n\n<p>\n<b>MakeBinaryFromARM(ARM_Instructions)</b>: Create the binar"
"y part of\na <tt>BinCFunction</tt> from ARM assembly code. Here, <tt>nativeMat"
"h</tt> and\n<tt>newtonScriptMath</tt> are both functions that can be called fr"
"om anywhere\nin a script:\n<p>\n<pre>\nnativeMath: {\n  class : \'BinCFunction"
",\n  numArgs: 2,\n  offset: 0,\n  code: MakeBinaryFromARM(\"\n    ldr r1, [r1]"
"          @ Unref the first argument\n    ldr r1, [r1]          @ Get the inte"
"ger object\n    mov r1, r1, lsr #2    @ convert it into an integer\n    ldr r2"
", [r2]\n    ldr r2, [r2]          @ do the same with the second arg\n    mov r"
"2, r2, lsr #2\n    add r0, r1, r2        @ add both integers\n    mov r0, r0, "
"lsl #2    @ convert the result into an integer object\n    mov pc, lr         "
"   @ return to the interpreter\n  \")\n}\n// The same in Newton Script\nnewton"
"ScriptMath: func(a, b) begin\n  return a+b;\nend\n</pre>\n\n<p>\n<b>MakeBinary"
"FromARMFile(ARM_Assembler_Filename)</b>: Same as above, but\ninstead of as str"
"ing with ARM instructions, this call takes a file path and\nname of an ARM ass"
"embler code file.\n\n<p>\n<b>AddStepForm(theParentView, myView)</b>: This is a"
"n original NTK function.\nIt ensures that the parent view has a frame named \""
"StepChildren\", and then\nadds <tt>myView</tt> to that frame. This is needed t"
"o ensure that a new view\nwill appear as a child of the parent view when an ap"
"p is opened.\n\n<p>\n<b>StepDeclare(theParentView, myView, \'myView)</b>: This"
" is an original NTK\nfunction. It ensures that the parent view has an array na"
"med\n\"StepAllocateContext\", and the appends <tt>myView</tt> and the symbol\n"
"<tt>\'myView</tt> to the array.\n\n<p>\n<b>_STDERR_</b>:\n\n<p>\n<b>_STDOUT_</"
"b>:\n\n<h2>FLTK extensions</h2>\n\n<b>fltk:message(message)</b>: Open a messag"
"e dialog box.\n\n<p>\n<b>fltk:choice(message, cancel_button, ok_button, opt_bu"
"tton)</b>:\nOpen a user choice dialog box and return the selected button id.\n"
"\n<p>\n<b>fltk:filechooser(message, pattern, filename, relative)</b>:\nOpen a "
"file chooser dialog. Returns filename or NIL.\n\n<h2>Host File Access extensio"
"ns</h2>\n\n<b>file:new()</b>: Create a frame to access files on the host machi"
"ne.\n\n<p>\n<b>file:open(filename, mode)</b>: Open a file, mode is \'read|\'wr"
"ite|\'readwrite|\'append.\n\n<p>\n<b>file:isOpen()</b>: Returns nil or true.\n"
"\n<p>\n<b>file:size()</b>: Returns file size in bytes.\n\n<p>\n<b>file:read(si"
"ze)</b>: Read up to size bytes and return a binary object with the data.\n\n<p"
">\n<b>file:write(binaryObject)</b>: Write the content of a binary object to a "
"file.\n\n<p>\n<b>file:seek(pos, mode)</b>: Set read position, mode is \'set|\'"
"cur|\'end.\n\n<p>\n<b>file:tell()</b>: Return the current read position in the"
" file.\n\n<p>\n<b>file:close()</b>: Closes a file, returns exception or true."
"\n\n</body>\n</html>\n";

TFlDropButton::TFlDropButton(int x, int y, int w, int h, const char *label) : Fl_Button(x, y, w, h, label) {
}

int TFlDropButton::handle(int e) {
  switch (e) {
    case FL_DND_ENTER: 
    case FL_DND_DRAG:
    case FL_DND_RELEASE:
      return 1;
    case FL_PASTE:
      if (callback())
        do_callback(this, (void*)Fl::event_text());
      return 1;
  }
  return Fl_Button::handle(e);
}

static void tk_open_recent_cb(Fl_Menu_Item *, void *u) {
  char *filename = ::strdup((char*)u);
  gToolkit->UserActionOpen(filename);
  ::free(filename);
}

static void add_proto_cb(Fl_Menu_Bar *mb, void *) {
  auto mi = mb->mvalue();
  if (mi)
    gToolkit->UserActionAddProto(mi->label());
}

Fl_Double_Window *wToolkitWindow=(Fl_Double_Window *)0;

TFLMenuBar *wToolkitMenubar=(TFLMenuBar *)0;

static void cb_New(Fl_Menu_*, void*) {
  gToolkit->UserActionNew();
}

static void cb_Open(Fl_Menu_*, void*) {
  gToolkit->UserActionOpen();
}

static void cb_Clear(Fl_Menu_*, void*) {
  gToolkit->ClearRecentFileMenu();
}

static void cb_Hello(Fl_Menu_*, void*) {
  gToolkit->LoadSampleCode(1);
}

static void cb_Miles(Fl_Menu_*, void*) {
  gToolkit->LoadSampleCode(2);
}

static void cb_Native(Fl_Menu_*, void*) {
  gToolkit->LoadSampleCode(3);
}

static void cb_ROM(Fl_Menu_*, void*) {
  gToolkit->LoadSampleCode(4);
}

static void cb_Save(Fl_Menu_*, void*) {
  gToolkit->UserActionSave();
}

static void cb_Save1(Fl_Menu_*, void*) {
  gToolkit->UserActionSaveAs();
}

static void cb_Close(Fl_Menu_*, void*) {
  gToolkit->UserActionClose();
}

static void cb_Quit(Fl_Menu_*, void*) {
  gToolkit->UserActionQuit();
}

static void cb_Undo(Fl_Menu_*, void*) {
  gToolkit->UserActionUndo();
}

static void cb_Redo(Fl_Menu_*, void*) {
  gToolkit->UserActionRedo();
}

static void cb_Cut(Fl_Menu_*, void*) {
  gToolkit->UserActionCut();
}

static void cb_Copy(Fl_Menu_*, void*) {
  gToolkit->UserActionCopy();
}

static void cb_Paste(Fl_Menu_*, void*) {
  gToolkit->UserActionPaste();
}

static void cb_Find(Fl_Menu_*, void*) {
  gToolkit->UserActionFind();
}

static void cb_Find1(Fl_Menu_*, void*) {
  gToolkit->UserActionFindNext();
}

static void cb_Find2(Fl_Menu_*, void*) {
  gToolkit->UserActionReplaceNext();
}

static void cb_Build(Fl_Menu_*, void*) {
  gToolkit->UserActionBuild();
}

static void cb_Install(Fl_Menu_*, void*) {
  gToolkit->UserActionInstall();
}

static void cb_Run(Fl_Menu_*, void*) {
  gToolkit->UserActionRun();
}

static void cb_Stop(Fl_Menu_*, void*) {
  gToolkit->UserActionStop();
}

static void cb_Process(Fl_Menu_*, void*) {
  gToolkit->AppInstall();
}

static void cb_Process1(Fl_Menu_*, void*) {
  gToolkit->AppBuild();
  gToolkit->AppInstall();
  gToolkit->AppRun();
}

static void cb_Project(Fl_Menu_*, void*) {
  gToolkit->AppStop();
}

static void cb_Toolkit(Fl_Menu_*, void*) {
  if (!tkHelpDialog) {
    tkHelpDialog = new Fl_Help_Dialog();
    tkHelpDialog->value(tkHelpText);
  }
  tkHelpDialog->show();
}

static void cb_Decompile(Fl_Menu_*, void*) {
  gToolkit->UserActionDecompilePkg();
}

Fl_Menu_Item menu_wToolkitMenubar[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"New...", FL_COMMAND|'n',  (Fl_Callback*)cb_New, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open...", FL_COMMAND|'o',  (Fl_Callback*)cb_Open, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open Recent", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"\n", 0,  (Fl_Callback*)tk_open_recent_cb, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Clear Menu", 0,  (Fl_Callback*)cb_Clear, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Sample Projects", 0,  0, 0, 192, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Hello World", 0,  (Fl_Callback*)cb_Hello, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Miles Per Gallon", 0,  (Fl_Callback*)cb_Miles, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Native Function", 0,  (Fl_Callback*)cb_Native, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"ROM Patcher", 0,  (Fl_Callback*)cb_ROM, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Save", FL_COMMAND|'s',  (Fl_Callback*)cb_Save, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Save As...", FL_COMMAND|FL_SHIFT|'s',  (Fl_Callback*)cb_Save1, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Close", FL_COMMAND|'w',  (Fl_Callback*)cb_Close, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Page Setup...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Print...", FL_COMMAND|'p',  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", FL_COMMAND|'q',  (Fl_Callback*)cb_Quit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Edit", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Undo", FL_COMMAND|'z',  (Fl_Callback*)cb_Undo, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Redo", FL_COMMAND|FL_SHIFT|'z',  (Fl_Callback*)cb_Redo, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Cut", FL_COMMAND|'x',  (Fl_Callback*)cb_Cut, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Copy", FL_COMMAND|'c',  (Fl_Callback*)cb_Copy, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Paste", FL_COMMAND|'v',  (Fl_Callback*)cb_Paste, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Find", FL_COMMAND|'f',  (Fl_Callback*)cb_Find, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Find Next", FL_COMMAND|'g',  (Fl_Callback*)cb_Find1, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Find And Replace", FL_COMMAND|FL_ALT|'f',  (Fl_Callback*)cb_Find2, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Project", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"New Project...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Open Project...", 0,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Add File...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Remove File", 0,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Build", FL_COMMAND|'b',  (Fl_Callback*)cb_Build, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Install", FL_COMMAND|'2',  (Fl_Callback*)cb_Install, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Run", FL_COMMAND|'r',  (Fl_Callback*)cb_Run, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Stop", FL_COMMAND|'.',  (Fl_Callback*)cb_Stop, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Process Earlier", 0xffbf,  (Fl_Callback*)cb_Process, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Process Later", 0xffc0,  (Fl_Callback*)cb_Process1, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Project Settings...", FL_COMMAND|'.',  (Fl_Callback*)cb_Project, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Protos", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"More cl Views", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clGaugeView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clKeyboardView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clMonthView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clOutline", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clRemoteView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"More protos", 0,  0, 0, 192, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoActionButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoBorder", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoDateExpando", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoDrawer", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoExpandoShell", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoFilingButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoFolderTab", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoGlance", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoKeyboard", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoKeypad", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoLabeledBatteryGauge", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPhoneExpando", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPicker", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPictIndexer", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPictRadionButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPrintFormat", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRoll", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRollBrowser", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRollItem", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoSetClock", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoStatusBar", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTable", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTableEntry", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTextList", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"clView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clParagraphView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clPictureView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clPolygonView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"clEditView", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoStaticText", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoApp", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoFloatNGo", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoFloater", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoStatus", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTitle", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRecToggle", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoLargeClosebox", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTextButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoPictureButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoCheckButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRCheckButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRadioButton", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoRadioCluster", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoCloseBox", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoLabelInputLine", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoInputLine", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoLabelPicker", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoDivider", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoGauge", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoSlider", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"protoTextExpando", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"LinkedSubview", 0,  (Fl_Callback*)add_proto_cb, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Help", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Toolkit Manual...", 0,  (Fl_Callback*)cb_Toolkit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Decompile Package...", 0,  (Fl_Callback*)cb_Decompile, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"About Toolkit...", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Group *wToolkitToolbar=(Fl_Group *)0;

Fl_Button *wToolkitRun=(Fl_Button *)0;

static void cb_wToolkitRun(Fl_Button*, void*) {
  gToolkit->UserActionRun();
}

Fl_Button *wToolkitStop=(Fl_Button *)0;

static void cb_wToolkitStop(Fl_Button*, void*) {
  gToolkit->UserActionStop();
}

TFlDropButton *wToolkitDecompile=(TFlDropButton *)0;

static void cb_wToolkitDecompile(TFlDropButton*, void* v) {
  gToolkit->UserActionDecompilePkg((char*)v);
}

Fl_Group *wToolkitFindGroup=(Fl_Group *)0;

Fl_Input *wToolkitFindText=(Fl_Input *)0;

static void cb_wToolkitFindText(Fl_Input*, void*) {
  gToolkit->UserActionFindTextChanged();
}

Fl_Input *wToolkitReplaceText=(Fl_Input *)0;

static void cb_wToolkitReplaceText(Fl_Input*, void*) {
  gToolkit->UserActionReplaceTextChanged();
}

Fl_Button *wToolkitFindCase=(Fl_Button *)0;

static void cb_wToolkitFindCase(Fl_Button*, void*) {
  gToolkit->UserActionCaseChanged();
}

Fl_Button *wToolkitFindRegex=(Fl_Button *)0;

static void cb_wToolkitFindRegex(Fl_Button*, void*) {
  gToolkit->UserActionRegexChanged();
}

Fl_Button *wToolkitFindPrev=(Fl_Button *)0;

static void cb_wToolkitFindPrev(Fl_Button*, void*) {
  gToolkit->UserActionFindPrev();
}

Fl_Button *wToolkitFindNext=(Fl_Button *)0;

static void cb_wToolkitFindNext(Fl_Button*, void*) {
  gToolkit->UserActionFindNext();
}

Fl_Button *wToolkitFindHide=(Fl_Button *)0;

static void cb_wToolkitFindHide(Fl_Button*, void*) {
  gToolkit->UserActionFindHide();
}

Fl_Button *wToolkitReplaceNext=(Fl_Button *)0;

static void cb_wToolkitReplaceNext(Fl_Button*, void*) {
  gToolkit->UserActionReplaceNext();
}

Fl_Button *wToolkitReplaceAll=(Fl_Button *)0;

static void cb_wToolkitReplaceAll(Fl_Button*, void*) {
  gToolkit->UserActionReplaceAll();
}

TFLTile *wTile=(TFLTile *)0;

TFLScriptPanel *wScriptPanel=(TFLScriptPanel *)0;

TFLTerminalEditor *wToolkitTerminal=(TFLTerminalEditor *)0;

Fl_Double_Window* CreateToolkitWindow(int x, int y) {
  { wToolkitWindow = new Fl_Double_Window(720, 600);
    { TFLMenuBar* o = wToolkitMenubar = new TFLMenuBar(0, 0, 720, 24);
      wToolkitMenubar->box(FL_UP_BOX);
      wToolkitMenubar->color(FL_LIGHT2);
      wToolkitMenubar->selection_color(FL_SELECTION_COLOR);
      wToolkitMenubar->labeltype(FL_NORMAL_LABEL);
      wToolkitMenubar->labelfont(0);
      wToolkitMenubar->labelsize(14);
      wToolkitMenubar->labelcolor(FL_FOREGROUND_COLOR);
      wToolkitMenubar->align(Fl_Align(FL_ALIGN_CENTER));
      wToolkitMenubar->when(FL_WHEN_RELEASE_ALWAYS);
        wTKOpenRecentMenu[0] = &menu_wToolkitMenubar[4];
        wTKOpenRecentMenu[1] = &menu_wToolkitMenubar[5];
        wTKOpenRecentMenu[2] = &menu_wToolkitMenubar[6];
        wTKOpenRecentMenu[3] = &menu_wToolkitMenubar[7];
        wTKOpenRecentMenu[4] = &menu_wToolkitMenubar[8];
        wTKOpenRecentMenu[5] = &menu_wToolkitMenubar[9];
        wTKOpenRecentMenu[6] = &menu_wToolkitMenubar[10];
        wTKOpenRecentMenu[7] = &menu_wToolkitMenubar[11];
      wToolkitMenubar->menu(menu_wToolkitMenubar);
      o->box(FL_FREE_BOXTYPE);
    } // TFLMenuBar* wToolkitMenubar
    { Fl_Group* o = wToolkitToolbar = new Fl_Group(0, 24, 720, 32);
      wToolkitToolbar->box(FL_THIN_UP_BOX);
      wToolkitToolbar->color(FL_LIGHT2);
      { Fl_Button* o = wToolkitRun = new Fl_Button(10, 28, 32, 24, "@>");
        wToolkitRun->color(FL_LIGHT2);
        wToolkitRun->labelsize(16);
        wToolkitRun->labelcolor((Fl_Color)48);
        wToolkitRun->callback((Fl_Callback*)cb_wToolkitRun);
        wToolkitRun->align(Fl_Align(512|FL_ALIGN_INSIDE));
        o->box(FL_FREE_BOXTYPE);
        o->down_box(FL_FREE_BOXTYPE);
        o->clear_visible_focus();
      } // Fl_Button* wToolkitRun
      { Fl_Button* o = wToolkitStop = new Fl_Button(46, 28, 32, 24, "@square");
        wToolkitStop->color(FL_LIGHT2);
        wToolkitStop->labelsize(10);
        wToolkitStop->labelcolor((Fl_Color)48);
        wToolkitStop->callback((Fl_Callback*)cb_wToolkitStop);
        wToolkitStop->align(Fl_Align(512|FL_ALIGN_INSIDE));
        o->box(FL_FREE_BOXTYPE);
        o->down_box(FL_FREE_BOXTYPE);
        o->clear_visible_focus();
      } // Fl_Button* wToolkitStop
      { TFlDropButton* o = wToolkitDecompile = new TFlDropButton(678, 28, 32, 24, "@refresh");
        wToolkitDecompile->tooltip("drop packes here to decompile them");
        wToolkitDecompile->box(FL_UP_BOX);
        wToolkitDecompile->color(FL_LIGHT2);
        wToolkitDecompile->selection_color(FL_BACKGROUND_COLOR);
        wToolkitDecompile->labeltype(FL_NORMAL_LABEL);
        wToolkitDecompile->labelfont(0);
        wToolkitDecompile->labelsize(10);
        wToolkitDecompile->labelcolor((Fl_Color)48);
        wToolkitDecompile->callback((Fl_Callback*)cb_wToolkitDecompile, (void*)(0L));
        wToolkitDecompile->align(Fl_Align(512|FL_ALIGN_INSIDE));
        wToolkitDecompile->when(FL_WHEN_RELEASE);
        o->box(FL_THIN_DOWN_BOX);
        o->down_box(FL_FREE_BOXTYPE);
        o->clear_visible_focus();
      } // TFlDropButton* wToolkitDecompile
      { Fl_Box* o = new Fl_Box(87, 30, 584, 26);
        o->hide();
        Fl_Group::current()->resizable(o);
      } // Fl_Box* o
      o->box(FL_FREE_BOXTYPE);
      wToolkitToolbar->end();
    } // Fl_Group* wToolkitToolbar
    { wToolkitFindGroup = new Fl_Group(0, 56, 720, 58);
      wToolkitFindGroup->box(FL_FLAT_BOX);
      wToolkitFindGroup->color(FL_LIGHT1);
      { Fl_Box* o = new Fl_Box(6, 62, 50, 20, "Replace");
        o->labelsize(11);
        o->align(Fl_Align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE));
      } // Fl_Box* o
      { Fl_Box* o = new Fl_Box(6, 88, 50, 20, "With");
        o->labelsize(11);
        o->align(Fl_Align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE));
      } // Fl_Box* o
      { Fl_Group* o = new Fl_Group(58, 62, 488, 46);
        { wToolkitFindText = new Fl_Input(58, 62, 488, 20);
          wToolkitFindText->color(FL_LIGHT3);
          wToolkitFindText->labelsize(11);
          wToolkitFindText->textfont(4);
          wToolkitFindText->textsize(12);
          wToolkitFindText->callback((Fl_Callback*)cb_wToolkitFindText);
          wToolkitFindText->when(FL_WHEN_NEVER);
          wToolkitFindText->when(FL_WHEN_ENTER_KEY_CHANGED);
        } // Fl_Input* wToolkitFindText
        { wToolkitReplaceText = new Fl_Input(58, 88, 488, 20);
          wToolkitReplaceText->color(FL_LIGHT3);
          wToolkitReplaceText->labelsize(11);
          wToolkitReplaceText->textfont(4);
          wToolkitReplaceText->textsize(12);
          wToolkitReplaceText->callback((Fl_Callback*)cb_wToolkitReplaceText);
          wToolkitReplaceText->when(FL_WHEN_CHANGED);
        } // Fl_Input* wToolkitReplaceText
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Group* o
      { wToolkitFindCase = new Fl_Button(556, 62, 32, 20, "Aa");
        wToolkitFindCase->type(1);
        wToolkitFindCase->color(FL_LIGHT1);
        wToolkitFindCase->labelsize(12);
        wToolkitFindCase->callback((Fl_Callback*)cb_wToolkitFindCase);
      } // Fl_Button* wToolkitFindCase
      { wToolkitFindRegex = new Fl_Button(588, 62, 32, 20, "[a]");
        wToolkitFindRegex->type(1);
        wToolkitFindRegex->color(FL_LIGHT1);
        wToolkitFindRegex->labelsize(12);
        wToolkitFindRegex->callback((Fl_Callback*)cb_wToolkitFindRegex);
        wToolkitFindRegex->deactivate();
      } // Fl_Button* wToolkitFindRegex
      { wToolkitFindPrev = new Fl_Button(626, 62, 32, 20, "<");
        wToolkitFindPrev->color(FL_LIGHT1);
        wToolkitFindPrev->labelsize(12);
        wToolkitFindPrev->callback((Fl_Callback*)cb_wToolkitFindPrev);
      } // Fl_Button* wToolkitFindPrev
      { wToolkitFindNext = new Fl_Button(658, 62, 32, 20, ">");
        wToolkitFindNext->color(FL_LIGHT1);
        wToolkitFindNext->labelsize(12);
        wToolkitFindNext->callback((Fl_Callback*)cb_wToolkitFindNext);
      } // Fl_Button* wToolkitFindNext
      { wToolkitFindHide = new Fl_Button(701, 58, 18, 18, "X");
        wToolkitFindHide->box(FL_FLAT_BOX);
        wToolkitFindHide->down_box(FL_DOWN_BOX);
        wToolkitFindHide->color((Fl_Color)51);
        wToolkitFindHide->labelsize(11);
        wToolkitFindHide->callback((Fl_Callback*)cb_wToolkitFindHide);
      } // Fl_Button* wToolkitFindHide
      { wToolkitReplaceNext = new Fl_Button(626, 88, 64, 20, "Replace");
        wToolkitReplaceNext->color(FL_LIGHT1);
        wToolkitReplaceNext->labelsize(12);
        wToolkitReplaceNext->callback((Fl_Callback*)cb_wToolkitReplaceNext);
      } // Fl_Button* wToolkitReplaceNext
      { wToolkitReplaceAll = new Fl_Button(690, 88, 24, 20, "All");
        wToolkitReplaceAll->color(FL_LIGHT1);
        wToolkitReplaceAll->labelsize(12);
        wToolkitReplaceAll->callback((Fl_Callback*)cb_wToolkitReplaceAll);
      } // Fl_Button* wToolkitReplaceAll
      wToolkitFindGroup->end();
    } // Fl_Group* wToolkitFindGroup
    { wTile = new TFLTile(0, 114, 720, 486);
      wTile->box(FL_NO_BOX);
      wTile->color(FL_BACKGROUND_COLOR);
      wTile->selection_color(FL_BACKGROUND_COLOR);
      wTile->labeltype(FL_NORMAL_LABEL);
      wTile->labelfont(0);
      wTile->labelsize(14);
      wTile->labelcolor(FL_FOREGROUND_COLOR);
      wTile->align(Fl_Align(FL_ALIGN_TOP));
      wTile->when(FL_WHEN_RELEASE);
      { wScriptPanel = new TFLScriptPanel(0, 114, 720, 386);
        wScriptPanel->box(FL_NO_BOX);
        wScriptPanel->color(FL_BACKGROUND_COLOR);
        wScriptPanel->selection_color(FL_BACKGROUND_COLOR);
        wScriptPanel->labeltype(FL_NORMAL_LABEL);
        wScriptPanel->labelfont(0);
        wScriptPanel->labelsize(14);
        wScriptPanel->labelcolor(FL_FOREGROUND_COLOR);
        wScriptPanel->align(Fl_Align(FL_ALIGN_TOP));
        wScriptPanel->when(FL_WHEN_RELEASE);
        wScriptPanel->end();
        Fl_Group::current()->resizable(wScriptPanel);
      } // TFLScriptPanel* wScriptPanel
      { wToolkitTerminal = new TFLTerminalEditor(0, 500, 720, 100);
        wToolkitTerminal->box(FL_THIN_DOWN_FRAME);
        wToolkitTerminal->color(FL_BACKGROUND2_COLOR);
        wToolkitTerminal->selection_color((Fl_Color)246);
        wToolkitTerminal->labeltype(FL_NORMAL_LABEL);
        wToolkitTerminal->labelfont(0);
        wToolkitTerminal->labelsize(14);
        wToolkitTerminal->labelcolor(FL_FOREGROUND_COLOR);
        wToolkitTerminal->textfont(4);
        wToolkitTerminal->align(Fl_Align(FL_ALIGN_TOP));
        wToolkitTerminal->when(FL_WHEN_RELEASE);
      } // TFLTerminalEditor* wToolkitTerminal
      wTile->end();
      Fl_Group::current()->resizable(wTile);
    } // TFLTile* wTile
    wToolkitWindow->position(x, y);
    wToolkitWindow->end();
  } // Fl_Double_Window* wToolkitWindow
  wScriptPanel->GetEditor()->take_focus();
  return wToolkitWindow;
}
