// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef TFLToolkitUI_h
#define TFLToolkitUI_h
#include <FL/Fl.H>
#include "Toolkit/TFLTerminalPanel.h"
#include <FL/Fl_Button.H>
#include "Toolkit/TFLScriptPanel.h"

/**
 // This button calls its callback with the text
 // that is dropped on it (for example, a filename)
*/
class TFlDropButton : public Fl_Button {
public:
  TFlDropButton(int x, int y, int w, int h, const char *label=nullptr) ;
protected:
  int handle(int e);
};
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *wToolkitWindow;
extern TFLMenuBar *wToolkitMenubar;
#include <FL/Fl_Group.H>
extern Fl_Group *wToolkitToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wToolkitRun;
extern Fl_Button *wToolkitStop;
extern TFlDropButton *wToolkitDecompile;
#include <FL/Fl_Box.H>
extern Fl_Group *wToolkitFindGroup;
#include <FL/Fl_Input.H>
extern Fl_Input *wToolkitFindText;
extern Fl_Input *wToolkitReplaceText;
extern Fl_Button *wToolkitFindCase;
extern Fl_Button *wToolkitFindRegex;
extern Fl_Button *wToolkitFindPrev;
extern Fl_Button *wToolkitFindNext;
extern Fl_Button *wToolkitFindHide;
extern Fl_Button *wToolkitReplaceNext;
extern Fl_Button *wToolkitReplaceAll;
extern TFLTile *wTile;
extern TFLScriptPanel *wScriptPanel;
extern TFLTerminalEditor *wToolkitTerminal;
Fl_Double_Window* CreateToolkitWindow(int x, int y);
extern Fl_Menu_Item menu_wToolkitMenubar[];
extern Fl_Menu_Item *wTKOpenRecentMenu[8];
void CreateProjectSettingsWindow();
#endif
