/**
 * Collection of transcoded functions
 */

#ifndef SimCollection1_H
#define SimCollection1_H

#include "SimulatorGlue.h"

#if 0

// This is code generated by the "rt" commands in the Monitor

extern void Func_0x00120010(TARMProcessor* ioCPU); // TMonitor::SetResult(...)

#endif

#endif

/**
 * End of transcoded functions
 */
