// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef TFLAppUI_h
#define TFLAppUI_h
#include <FL/Fl.H>
#include "TFLAppWindow.h"
#include "TFLTabs.h"
extern unsigned char imgPCCardTopIn[508];
extern unsigned char imgPCCardTopOut[571];
extern unsigned char imgPCCardTopHilite[1117];
extern unsigned char imgPCCardBotIn[514];
extern unsigned char imgPCCardBotOut[565];
extern unsigned char imgPCCardBotHilite[1118];
extern TFLAppWindow *wAppWindow;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *wMenubar;
#include "Emulator/JIT/TJITStatistics.h"
#include <FL/Fl_Group.H>
extern Fl_Group *wToolbar;
#include <FL/Fl_Button.H>
extern Fl_Button *wPowerTool;
extern Fl_Button *wPowerOnTool;
extern Fl_Button *wBacklightTool;
extern Fl_Button *wBacklightOnTool;
extern TFLPCMCIAButton *wNetworkTool;
extern Fl_Button *wNetworkOnTool;
#include <FL/Fl_Box.H>
extern Fl_Box *wSpacer;
TFLAppWindow* CreateApplicationWindow(int x, int y);
extern Fl_Menu_Item menu_wMenubar[];
#define wPCCardSlot1 (menu_wMenubar+26)
#define wPCCardSlot0 (menu_wMenubar+27)
#define wMenuItemFullscreen (menu_wMenubar+40)
#define wMenuItemMonitor (menu_wMenubar+41)
#define wMenuItemToolkit (menu_wMenubar+42)
#define wMenuItemEssentials (menu_wMenubar+49)
#define wMenuItemAbout (menu_wMenubar+50)
#endif
