// ==============================
// File:			TFLSettings
// Project:			Einstein
//
// Copyright 2003-2022 by Paul Guyot (pguyot@kallisys.net).
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
// ==============================
// $Id$
// ==============================

// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef TFLSettingsUI_h
#define TFLSettingsUI_h
#include <FL/Fl.H>
class TFLApp;
#include "TFLSettings.h"
#include "TFLApp.h"
#if TARGET_OS_MAC
#include <FL/Fl_Sys_Menu_Bar.H>
#endif
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *wInstallerWindow;
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Pack.H>
extern Fl_Pack *wInstallerList;
Fl_Double_Window* makeInstaller();
#include <FL/Fl_Box.H>
Fl_Group* addInstallerTitle(const char *inTitle);
Fl_Group* addInstallerGroup(const char *inTitle);
extern Fl_Group *wInstallerTextGroup;
Fl_Group* addInstallerText(const char *inText);
#include <FL/Fl_Button.H>
Fl_Group* addInstallerPackage(const char *inTitle, StringList *inCmdList);
Fl_Group* addInstallerLink(const char *inTitle, StringList *inLinkList);
Fl_Group* addInstallerScript(const char *inTitle, StringList *inScriptList);
#include <FL/Fl_Menu_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Menu_Bar.H>
extern void cb_New(Fl_Menu_*, long);
extern void cb_New1(Fl_Menu_*, long);
#include <FL/Fl_Help_View.H>

class TFLSettingsUI : public TFLSettings {
public:
  TFLSettingsUI();
  Fl_Double_Window* CreateSettingsPanel();
private:
  inline void cb_Einstein_i(Fl_Double_Window*, void*);
  static void cb_Einstein(Fl_Double_Window*, void*);
public:
  Fl_Menu_Button *RMB;
  static Fl_Menu_Item menu_RMB[];
private:
  inline void cb_Install1_i(Fl_Menu_*, void*);
  static void cb_Install1(Fl_Menu_*, void*);
  inline void cb_Backlight_i(Fl_Menu_*, void*);
  static void cb_Backlight(Fl_Menu_*, void*);
  inline void cb_Settings_i(Fl_Menu_*, void*);
  static void cb_Settings(Fl_Menu_*, void*);
  inline void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
  inline void cb_Power_i(Fl_Menu_*, void*);
  static void cb_Power(Fl_Menu_*, void*);
public:
  Fl_Input *wMPConfigName;
  Fl_Button *wMPConfigMenuButton;
  Fl_Button *wMPConfigAddButton;
  Fl_Button *wMPConfigRemoveButton;
  Fl_Input *wROMName;
private:
  inline void cb_wROMName_i(Fl_Input*, void*);
  static void cb_wROMName(Fl_Input*, void*);
public:
  Fl_Box *wROMPath;
  Fl_Box *wROMDetails;
  Fl_Button *wROMPathChoose;
private:
  inline void cb_wROMPathChoose_i(Fl_Button*, void*);
  static void cb_wROMPathChoose(Fl_Button*, void*);
public:
  Fl_Input *wFlashName;
private:
  inline void cb_wFlashName_i(Fl_Input*, void*);
  static void cb_wFlashName(Fl_Input*, void*);
public:
  Fl_Box *wFlashPath;
  Fl_Button *wFlashPathCreate;
private:
  inline void cb_wFlashPathCreate_i(Fl_Button*, void*);
  static void cb_wFlashPathCreate(Fl_Button*, void*);
public:
  Fl_Button *wFlashPathChoose;
private:
  inline void cb_wFlashPathChoose_i(Fl_Button*, void*);
  static void cb_wFlashPathChoose(Fl_Button*, void*);
public:
  Fl_Choice *wRAMSizeChoice;
  static Fl_Menu_Item menu_wRAMSizeChoice[];
  static Fl_Menu_Item menu_User[];
  Fl_Box *wRestartWarning;
  Fl_Check_Button *wFetchDateAndTime;
  Fl_Int_Input *wWidth;
  Fl_Int_Input *wHeight;
  Fl_Check_Button *wFullScreen;
  Fl_Check_Button *wHideMouse;
  Fl_Check_Button *wLaunchMonitorAtBoot;
  Fl_Check_Button *wBreakAtROMBoot;
  Fl_Check_Button *wShowMenubar;
  Fl_Check_Button *wShowToolbar;
  Fl_Input_Choice *wScale;
  static Fl_Menu_Item menu_wScale[];
  Fl_Input *wUIConfigName;
  Fl_Button *wUIConfigMenuButton;
  Fl_Button *wUIConfigAddButton;
  Fl_Button *wUIConfigRemoveButton;
  Fl_Browser *wPCCardList;
private:
  inline void cb_wPCCardList_i(Fl_Browser*, void*);
  static void cb_wPCCardList(Fl_Browser*, void*);
  static Fl_Menu_Item menu_[];
  inline void cb_Add_i(Fl_Menu_*, void*);
  static void cb_Add(Fl_Menu_*, void*);
  inline void cb_New_i(Fl_Menu_*, void*);
  static void cb_New(Fl_Menu_*, void*);
  inline void cb_Create_i(Fl_Menu_*, void*);
  static void cb_Create(Fl_Menu_*, void*);
  inline void cb_New1_i(Fl_Menu_*, void*);
  static void cb_New1(Fl_Menu_*, void*);
public:
  Fl_Button *wPCCardListRemove;
private:
  inline void cb_wPCCardListRemove_i(Fl_Button*, void*);
  static void cb_wPCCardListRemove(Fl_Button*, void*);
public:
  Fl_Button *wPCCardMoveUp;
private:
  inline void cb_wPCCardMoveUp_i(Fl_Button*, void*);
  static void cb_wPCCardMoveUp(Fl_Button*, void*);
public:
  Fl_Button *wPCCardMoveDown;
private:
  inline void cb_wPCCardMoveDown_i(Fl_Button*, void*);
  static void cb_wPCCardMoveDown(Fl_Button*, void*);
  static Fl_Menu_Item menu_1[];
public:
  static Fl_Menu_Item *wPCCardEditName;
private:
  inline void cb_wPCCardEditName_i(Fl_Menu_*, void*);
  static void cb_wPCCardEditName(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *wPCCardEditTag;
private:
  inline void cb_wPCCardEditTag_i(Fl_Menu_*, void*);
  static void cb_wPCCardEditTag(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *wPCCardEditPath;
private:
  inline void cb_wPCCardEditPath_i(Fl_Menu_*, void*);
  static void cb_wPCCardEditPath(Fl_Menu_*, void*);
public:
  Fl_Input_Choice *wUnnaPath;
  static Fl_Menu_Item menu_wUnnaPath[];
  Fl_Button *wUnnaPathChoose;
private:
  inline void cb_wUnnaPathChoose_i(Fl_Button*, void*);
  static void cb_wUnnaPathChoose(Fl_Button*, void*);
public:
  Fl_Input_Choice *wMessagepadOrgPath;
  static Fl_Menu_Item menu_wMessagepadOrgPath[];
  Fl_Input_Choice *wGitRepoPath;
  static Fl_Menu_Item menu_wGitRepoPath[];
  Fl_Input *wDevAsmPath;
  Fl_Button *wDevAsmPathChoose;
private:
  inline void cb_wDevAsmPathChoose_i(Fl_Button*, void*);
  static void cb_wDevAsmPathChoose(Fl_Button*, void*);
public:
  Fl_Input *wDevObjCopyPath;
  Fl_Button *wDevObjCopyPathChoose;
private:
  inline void cb_wDevObjCopyPathChoose_i(Fl_Button*, void*);
  static void cb_wDevObjCopyPathChoose(Fl_Button*, void*);
public:
  Fl_Input *wDevObjDumpPath;
  Fl_Button *wDevObjDumpPathChoose;
private:
  inline void cb_wDevObjDumpPathChoose_i(Fl_Button*, void*);
  static void cb_wDevObjDumpPathChoose(Fl_Button*, void*);
public:
  Fl_Check_Button *wDontShow;
  Fl_Button *wQuit;
private:
  inline void cb_wQuit_i(Fl_Button*, void*);
  static void cb_wQuit(Fl_Button*, void*);
public:
  Fl_Button *wStart;
private:
  inline void cb_wStart_i(Fl_Button*, void*);
  static void cb_wStart(Fl_Button*, void*);
public:
  Fl_Button *wRevert;
private:
  inline void cb_wRevert_i(Fl_Button*, void*);
  static void cb_wRevert(Fl_Button*, void*);
public:
  Fl_Button *wSave;
private:
  inline void cb_wSave_i(Fl_Button*, void*);
  static void cb_wSave(Fl_Button*, void*);
public:
  void updateMenus();
  void revertDialog();
  void applyDialog();
  void runningMode();
private:
  void close_window_cb(Fl_Widget*, void *user);
public:
  Fl_Double_Window* createAboutDialog();
  Fl_Double_Window *wAbout;
private:
  inline void cb_wAbout_i(Fl_Double_Window*, void*);
  static void cb_wAbout(Fl_Double_Window*, void*);
  inline void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  void HandlePopupMenu();
#if TARGET_OS_MAC
  Fl_Sys_Menu_Bar *wSysMenubar = nullptr;
#endif
};
#endif

// ======================================================== //
// Of course the code works. It just compiled, didn't it?   //
// --helixcode123, 11/8/2001 on slashdot.                   //
// ======================================================== //


