#
# Convert a binary file into a C++ source file and header file containing a
# byte array. This runs as a script at build time, so the output is updated
# whenever the binary file changes, and it works when cross compiling.
#
# Usage:
#   cmake -D INPUT=<binary file> -D OUTPUT_CPP=<.cpp file> -D OUTPUT_H=<.h file>
#         -D NAME=<variable name> -P EmbedResource.cmake
#

foreach ( var INPUT OUTPUT_CPP OUTPUT_H NAME )
	if ( NOT DEFINED ${var} )
		message ( FATAL_ERROR "EmbedResource.cmake: ${var} is not set." )
	endif ()
endforeach ()

file ( SIZE "${INPUT}" size )
file ( READ "${INPUT}" hex_content HEX )

# 16 bytes per line, each byte as 0x.., separated by commas
string ( REPEAT "[0-9a-f]" 32 column_pattern )
string ( REGEX REPLACE "(${column_pattern})" "\\1\n" content "${hex_content}" )
string ( REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," content "${content}" )
string ( REGEX REPLACE ",$" "" content "${content}" )

get_filename_component ( input_name "${INPUT}" NAME )
get_filename_component ( header_name "${OUTPUT_H}" NAME )
get_filename_component ( guard "${OUTPUT_H}" NAME_WE )

file ( WRITE "${OUTPUT_H}"
	"// Generated by CMake from ${input_name}. Do not edit.\n\n"
	"#ifndef ${guard}_h\n"
	"#define ${guard}_h\n\n"
	"extern const unsigned char ${NAME}[${size}];\n\n"
	"#endif\n"
)

file ( WRITE "${OUTPUT_CPP}"
	"// Generated by CMake from ${input_name}. Do not edit.\n\n"
	"#include \"${header_name}\"\n\n"
	"const unsigned char ${NAME}[${size}] = {\n"
	"${content}\n"
	"};\n"
)
