name: CI macOS (FLTK)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Get dependencies
      run: brew install clang-format
    - name: Get sources
      uses: actions/checkout@v4
    - name: Configure Einstein
      run: |
        cmake -S . -B _Build_/Makefiles
    - name: Check format
      run: |
        cmake --build _Build_/Makefiles --target clang-format-check
    - name: Compile Einstein
      run: |
        cmake --build _Build_/Makefiles
    - name: Run tests
      run: |
        _Build_/Makefiles/EinsteinTests
