name: REx compilation

on:
  workflow_dispatch:
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get dependencies
      run: sudo apt-get install -y gcc-arm-none-eabi cmake make
    - name: Get Einstein sources
      uses: actions/checkout@v4
      with:
          path: Einstein
    - name: Compile the REx
      run: |
        cmake -S Einstein/Drivers -B Einstein/Drivers/build
        cmake --build Einstein/Drivers/build
    - name: Store the REx
      uses: actions/upload-artifact@v4
      with:
        name: Einstein.rex
        path: Einstein/_Data_/Einstein.rex
